name: CI

on:
  pull_request:
    branches: [ master, develop, release/** ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Event toJSON
        run: |
          echo "${{ toJSON(github.event) }}"
